bookers2/config/routes.rb
Rails.application.routes.draw do

  root to:'homes#top'
  get '/home/about' => 'users#about'

  devise_for :users
  resources :users, only:[:edit,:update]
  post 'users/:user_id/relationships' => 'relationships#create', as: 'user_relationships'
  delete 'users/:user_id/relationships/:id' => 'relationships#destroy', as: 'user_relationship'
  get 'users/:user_id/followings' => 'relationships#followings', as: 'followings'
  get 'users/:user_id/followers' => 'relationships#followers', as: 'followers'

  # ユーザー一覧(Users)
  get 'users' => 'users#userindex'
  #1ユーザーの投稿一覧(Home)
  get 'users/:id' => 'users#usershow', as: 'usershow'

  resources :books, only:[:create,:update,:destroy]

  # 投稿一覧(Books)
  get 'books' => 'users#bookindex', as: 'bookindex'

  # 現在のユーザーの投稿詳細(User=>show)
  get 'books/:id' => 'books#show', as: 'bookshow'
  post 'books/:id/favorites/' => 'favorites#create'
  delete 'books/:id/favorites/' => 'favorites#destroy', as: 'book_favorites'
  post 'books/:book_id/post_comments' => 'book_comments#create', as: 'book_book_comments'
  delete 'books/:book_id/post_comments/:id' => 'book_comments#destroy', as: 'book_book_comment'

  get 'books/:id/edit' => 'books#edit'
  post 'books/:id/edit' => 'books#edit', as: 'edit_book'

  #検索機能
  post '/search' => 'searchs#search', as: 'search'

  #グループ機能
  resources :groups do
    resources :group_users, only:[:create,:destroy]
    resources :mails, only:[:new, :create, :show]
  end

end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

bookers2/app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  attachment :image

  has_many :mails, dependent: :destroy

  def grouped_by?(user)
    group_users.where(user_id: user.id).exists?
  end

end

bookers2/app/models/group_user.rb
class GroupUser < ApplicationRecord

  belongs_to :user
  belongs_to :group

end

bookers2/app/models/mail.rb
class Mail < ApplicationRecord

  belongs_to :group

end

bookers2/app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image

  validates :name, uniqueness: true,
                   length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  
  has_many :group_users, dependent: :destroy

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      user_id = current_user.id
      @user = User.find_by(id:user_id)
      @newbook = Book.new
      @books = Book.all
      render 'users/bookindex'
    end
  end

  def show
    @book = Book.find(params[:id])
    user_id = @book.user_id
    @user = User.find(user_id)
    @newbook = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to bookindex_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have editted book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to bookindex_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/group_users_helper.rb
module GroupUsersHelper
end

bookers2/app/helpers/groups_helper.rb
module GroupsHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/mails_helper.rb
module MailsHelper
end

bookers2/app/helpers/searchs_helper.rb
module SearchsHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="navbar-collapse collapse" id="navbarNavDropdown" style>
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to "Home", usershow_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "Users",'/users', class: 'fas fa-users nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "Books",bookindex_path, class: 'fas fa-book-open nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "logout",destroy_user_session_path, class: 'fas fa-sign-out-alt nav-link text-light',method: :delete %>
                </li>
              <% else %>
                <li>
                  <%= link_to "Home",'/', class: 'fas fa-home nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "About",'/home/about', class: 'fas fa-link nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "sign up",new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
                </li>
                <li>
                  <%= link_to "login",new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <% if user_signed_in? %>
      <div class="search_box">
        <%= form_with url: search_path, method: :post, local: true do |f| %>
          <%= f.text_field :keyword %>

          <%= f.select :ubg, [["User","1"],["Book","2"],["Group"]], selected: 1 %>
          <%= f.select :moji, [["完全一致","1"],["前方一致","2"],["後方一致","3"],["部分一致","4"]], selected: 1 %>
          <%= f.submit '検索' %>
        <% end %>
      </div>
    <% end %>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>