bookers2/config/routes.rb
Rails.application.routes.draw do

  root to:'homes#top'
  get '/home/about' => 'users#about'

  devise_for :users
  resources :users, only:[:edit,:update]
  post 'users/:user_id/relationships' => 'relationships#create', as: 'user_relationships'
  delete 'users/:user_id/relationships/:id' => 'relationships#destroy', as: 'user_relationship'
  get 'users/:user_id/followings' => 'relationships#followings', as: 'followings'
  get 'users/:user_id/followers' => 'relationships#followers', as: 'followers'

  # ユーザー一覧(Users)
  get 'users' => 'users#userindex'
  #1ユーザーの投稿一覧(Home)
  get 'users/:id' => 'users#usershow', as: 'usershow'

  resources :books, only:[:create,:update,:destroy]

  # 投稿一覧(Books)
  get 'books' => 'users#bookindex', as: 'bookindex'

  # 現在のユーザーの投稿詳細(User=>show)
  get 'books/:id' => 'books#show', as: 'bookshow'
  post 'books/:id/favorites/' => 'favorites#create'
  delete 'books/:id/favorites/' => 'favorites#destroy', as: 'book_favorites'
  post 'books/:book_id/post_comments' => 'book_comments#create', as: 'book_book_comments'
  delete 'books/:book_id/post_comments/:id' => 'book_comments#destroy', as: 'book_book_comment'

  get 'books/:id/edit' => 'books#edit'
  post 'books/:id/edit' => 'books#edit', as: 'edit_book'

  #検索機能
  post '/search' => 'searchs#search', as: 'search'

  #グループ機能
  resources :groups do
    resources :group_users, only:[:create,:destroy]
    resources :mails, only:[:new, :create, :show]
  end

end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

bookers2/app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  attachment :image

  has_many :mails, dependent: :destroy

  def grouped_by?(user)
    group_users.where(user_id: user.id).exists?
  end

end

bookers2/app/models/group_user.rb
class GroupUser < ApplicationRecord

  belongs_to :user
  belongs_to :group

end

bookers2/app/models/mail.rb
class Mail < ApplicationRecord

  belongs_to :group

end

bookers2/app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image

  validates :name, uniqueness: true,
                   length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  
  has_many :group_users, dependent: :destroy

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      user_id = current_user.id
      @user = User.find_by(id:user_id)
      @newbook = Book.new
      @books = Book.all
      render 'users/bookindex'
    end
  end

  def show
    @book = Book.find(params[:id])
    user_id = @book.user_id
    @user = User.find(user_id)
    @newbook = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to bookindex_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have editted book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to bookindex_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers2/app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      flash[:notice] = "You have created group successfully."
      redirect_to groups_path
    else
      render :new
    end
  end

  def index
    @user_id = current_user.id
    @user = User.find(@user_id)
    @newbook = Book.new
    @groups = Group.all
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash[:notice] = "You have editted group successfully."
      redirect_to groups_path
    else
      render :edit
    end
  end

  def show
    @user_id = current_user.id
    @user = User.find(@user_id)
    @newbook = Book.new
    @group = Group.find(params[:id])
    @owner_user = User.find(@group.owner_id)
    @group_users = GroupUser.where(group_id: @group.id)
    @mails = Mail.where(group_id: @group.id)
  end

  def destroy
    @group = Group.find(params[:id])
    @group.delete
    flash[:notice] = "You have destroyed group successfully."
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

bookers2/app/controllers/mails_controller.rb
class MailsController < ApplicationController

  def new
    @mail = Mail.new
  end

  def create
    @group = Group.find(params[:group_id])
    @mail = Mail.new(mail_params)
    @mail.group_id = @group.id
    if @mail.save
      flash[:notice] = "送信が完了しました"
      redirect_to group_mail_path(group_id: @group.id, id: @mail.id)
    else
      render :new
    end
  end

  def show
    @mail = Mail.find(params[:id])
  end

  private

  def mail_params
    params.require(:mail).permit(:title, :content)
  end


end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def userindex
    @user_id = current_user.id
    @user = User.find(@user_id)
    @newbook = Book.new
    @users = User.all
  end

  def bookindex
    @book = Book.new
    user_id = current_user.id
    @user = User.find_by(id:user_id)
    @newbook = Book.new
    @books = Book.all
  end

  def about
  end

  def usershow
    @user = User.find(params[:id])
    @user_id = @user.id
    @books = Book.where(user_id:@user_id)
    @newbook = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to usershow_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have editted user info successfully."
      redirect_to usershow_path(current_user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end

end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/helpers/group_users_helper.rb
module GroupUsersHelper
end

bookers2/app/helpers/groups_helper.rb
module GroupsHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/mails_helper.rb
module MailsHelper
end

bookers2/app/helpers/searchs_helper.rb
module SearchsHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/groups/edit.html.erb
<h2 >Create Group</h2>

<%= form_with model:@group, local:true do |f| %>

  <div class="form-group">
    <label for="group_title">グループ名</label>
    <%= f.text_field :name, :class => 'form-control group_title', :id => 'group_title' %>
  </div>
  <div class="form-group">
    <label for="group_opinion">紹介文</label>
    <%= f.text_area :introduction, :class => 'form-control group_introduction', :id => 'group_introduction' %>
  </div>
  <div class="form-group">
    <label for="group_image">グループ画像</label>
    <%= f.attachment_field :image, placeholder: "プロフィール画像", :class => 'form-control-file group_image' %>
  </div>


  <div class="form-group">
    <%= f.submit 'Update Group', :class => 'btn btn-success' %>
  </div>

<% end %>

bookers2/app/views/groups/index.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <p id="notice"><%= flash[:notice] %></p>
  </div>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "person.jpg", size:'60x60' %>
        <table>
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= @user.followings.count %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= @user.followers.count %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <%= link_to '',edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>

      <h2 class="mt-3">New book</h2>

      <%= form_with model:@newbook,local:true do |f| %>

        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, :class => 'form-control book_title', :id => 'book_title' %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, :class => 'form-control book_body', :id => 'book_body' %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', :class => 'btn btn-success' %>
        </div>

      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>

      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー数</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @groups.each do |group|%>
            <tr>
              <td><%= attachment_image_tag group, :image, :fill, 60, 60, fallback: "person.jpg", size:'60x60' %></td>
              <td><%= link_to (group.name), group_path(group.id) %></td>
              <td><%= group.introduction %></td>
              <td><%= (group.group_users.count + 1) %></td>
              <% if group.owner_id == current_user.id %>
                <td><%= link_to "Edit",edit_group_path(group.id), :class => 'btn btn-sm btn-success' %></td>
                <td><%= link_to "Destroy",group_path(group.id), :class => 'btn btn-sm btn-danger', method: :delete, "data-confirm" => "ホンマに削除するん？、ええんやな？？" %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

bookers2/app/views/groups/new.html.erb
<h2 >Create Group</h2>

<%= form_with model:@group, local:true do |f| %>

  <div class="form-group">
    <label for="group_title">グループ名</label>
    <%= f.text_field :name, :class => 'form-control group_title', :id => 'group_title' %>
  </div>
  <div class="form-group">
    <label for="group_opinion">紹介文</label>
    <%= f.text_area :introduction, :class => 'form-control group_introduction', :id => 'group_introduction' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Create Group', :class => 'btn btn-success' %>
  </div>

<% end %>

bookers2/app/views/groups/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "person.jpg", size:'60x60' %>
        <table>
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= @user.followings.count %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= @user.followers.count %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <%= link_to '',edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>

      <h2 class="mt-3">New book</h2>

      <%= form_with model:@newbook,local:true do |f| %>

        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, :class => 'form-control book_title', :id => 'book_title' %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, :class => 'form-control book_body', :id => 'book_body' %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', :class => 'btn btn-success' %>
        </div>

      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Group Detail</h2>

      <table class="table">

        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td><%= attachment_image_tag @group, :image, :fill, 60, 60, fallback: "person.jpg", size:'60x60' %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <%= @owner_user.name %></br>
              <%  @group_users.each do |group_user| %>
                <%= group_user.user.name %></br>
              <% end %>
            </td>

            <% if @group.owner_id == current_user.id %>
              <td><%= link_to "Edit",edit_group_path(@group.id), :class => 'btn btn-sm btn-success' %></td>
            <% end %>

            <% if @group.owner_id == current_user.id %>

              <td><%= link_to "Notice an Event", new_group_mail_path(group_id: @group.id) %></td>

            <% else %>
              <% if @group.grouped_by?(current_user) %>
                <td><%= link_to "Leave this group",group_group_user_path(group_id: @group.id), method: :delete %></td>
              <% else %>
                <td><%= link_to "Join this group",group_group_users_path(group_id: @group.id), method: :post %></td>
              <% end %>
            <% end %>

          </tr>
        </tbody>
      </table>

      <% if (@group.owner_id == current_user.id) || (@group.grouped_by?(current_user)) %>
        <nav>
          <ol>
            <% @mails.each do |mail| %>
                <li><%= link_to "メール",group_mail_path(group_id: @group.id, id: mail.id) %></li>
            <% end %>
          </ol>
        </nav>
      <% end %>

    </div>
  </div>
</div>